[2024-02-09T06:34:13.706+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 8_minio.sensor_minio_s3 manual__2024-02-09T06:34:12.048299+00:00 [queued]>
[2024-02-09T06:34:13.720+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 8_minio.sensor_minio_s3 manual__2024-02-09T06:34:12.048299+00:00 [queued]>
[2024-02-09T06:34:13.721+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-09T06:34:13.742+0000] {taskinstance.py:2191} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2024-02-09 06:34:12.048299+00:00
[2024-02-09T06:34:13.748+0000] {standard_task_runner.py:60} INFO - Started process 15493 to run task
[2024-02-09T06:34:13.752+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '8_minio', 'sensor_minio_s3', 'manual__2024-02-09T06:34:12.048299+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/8_minio.py', '--cfg-path', '/tmp/tmps6eeqzdx']
[2024-02-09T06:34:13.755+0000] {standard_task_runner.py:88} INFO - Job 123: Subtask sensor_minio_s3
[2024-02-09T06:34:13.817+0000] {task_command.py:423} INFO - Running <TaskInstance: 8_minio.sensor_minio_s3 manual__2024-02-09T06:34:12.048299+00:00 [running]> on host b508da3c4080
[2024-02-09T06:34:13.924+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cardthp' AIRFLOW_CTX_DAG_ID='8_minio' AIRFLOW_CTX_TASK_ID='sensor_minio_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-09T06:34:12.048299+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-09T06:34:12.048299+00:00'
[2024-02-09T06:34:13.925+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-02-09T06:34:13.937+0000] {base.py:83} INFO - Using connection ID 'minio_conn' for task execution.
[2024-02-09T06:34:13.938+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2024-02-09T06:34:13.947+0000] {logging_mixin.py:188} WARNING - <string>:9 AirflowProviderDeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead
[2024-02-09T06:34:19.657+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-02-09T06:34:24.671+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-02-09T06:34:29.683+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-02-09T06:34:34.695+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-02-09T06:34:39.737+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-02-09T06:34:44.748+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-02-09T06:34:44.755+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 144, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 282, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 30.830214782996336 seconds exceeds the specified timeout of 30.0.
[2024-02-09T06:34:44.766+0000] {taskinstance.py:1138} INFO - Immediate failure requested. Marking task as FAILED. dag_id=8_minio, task_id=sensor_minio_s3, execution_date=20240209T063412, start_date=20240209T063413, end_date=20240209T063444
[2024-02-09T06:34:44.796+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 123 for task sensor_minio_s3 (Sensor has timed out; run duration of 30.830214782996336 seconds exceeds the specified timeout of 30.0.; 15493)
[2024-02-09T06:34:44.827+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-09T06:34:44.877+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
