[2024-02-09T06:34:11.367+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 8_minio.sensor_minio_s3 manual__2024-02-09T06:32:30.008015+00:00 [queued]>
[2024-02-09T06:34:11.386+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 8_minio.sensor_minio_s3 manual__2024-02-09T06:32:30.008015+00:00 [queued]>
[2024-02-09T06:34:11.387+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 8
[2024-02-09T06:34:11.416+0000] {taskinstance.py:2191} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2024-02-09 06:32:30.008015+00:00
[2024-02-09T06:34:11.424+0000] {standard_task_runner.py:60} INFO - Started process 15491 to run task
[2024-02-09T06:34:11.430+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '8_minio', 'sensor_minio_s3', 'manual__2024-02-09T06:32:30.008015+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/8_minio.py', '--cfg-path', '/tmp/tmp5i7j4wq1']
[2024-02-09T06:34:11.435+0000] {standard_task_runner.py:88} INFO - Job 122: Subtask sensor_minio_s3
[2024-02-09T06:34:11.517+0000] {task_command.py:423} INFO - Running <TaskInstance: 8_minio.sensor_minio_s3 manual__2024-02-09T06:32:30.008015+00:00 [running]> on host b508da3c4080
[2024-02-09T06:34:11.651+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cardthp' AIRFLOW_CTX_DAG_ID='8_minio' AIRFLOW_CTX_TASK_ID='sensor_minio_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-09T06:32:30.008015+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-09T06:32:30.008015+00:00'
[2024-02-09T06:34:11.653+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-02-09T06:34:11.668+0000] {base.py:83} INFO - Using connection ID 'minio_conn' for task execution.
[2024-02-09T06:34:11.670+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2024-02-09T06:34:11.683+0000] {logging_mixin.py:188} WARNING - <string>:9 AirflowProviderDeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead
[2024-02-09T06:34:17.852+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-02-09T06:34:22.865+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-02-09T06:34:27.879+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-02-09T06:34:32.892+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-02-09T06:34:37.904+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-02-09T06:34:42.921+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-02-09T06:34:42.927+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 144, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 282, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 31.274368198006414 seconds exceeds the specified timeout of 30.0.
[2024-02-09T06:34:42.935+0000] {taskinstance.py:1138} INFO - Immediate failure requested. Marking task as FAILED. dag_id=8_minio, task_id=sensor_minio_s3, execution_date=20240209T063230, start_date=20240209T063411, end_date=20240209T063442
[2024-02-09T06:34:42.952+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 122 for task sensor_minio_s3 (Sensor has timed out; run duration of 31.274368198006414 seconds exceeds the specified timeout of 30.0.; 15491)
[2024-02-09T06:34:42.986+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-09T06:34:43.028+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
